export const voices = [
  { name: "Leo", gender: "Male", age: "Kid", tone: "Soft" },
  { name: "Max", gender: "Male", age: "Kid", tone: "Gentle" },
  { name: "Oscar", gender: "Male", age: "Kid", tone: "Bright" },
  { name: "Ethan", gender: "Male", age: "Teen", tone: "Soft" },
  { name: "Noah", gender: "Male", age: "Teen", tone: "Gentle" },
  { name: "Lucas", gender: "Male", age: "Teen", tone: "Bright" },
  { name: "Arthur", gender: "Male", age: "Elder", tone: "Soft" },
  { name: "Henry", gender: "Male", age: "Elder", tone: "Gentle" },
  { name: "Edward", gender: "Male", age: "Elder", tone: "Bright" },
  { name: "Mia", gender: "Female", age: "Kid", tone: "Soft" },
  { name: "Lily", gender: "Female", age: "Kid", tone: "Gentle" },
  { name: "Ruby", gender: "Female", age: "Kid", tone: "Bright" },
  { name: "Chloe", gender: "Female", age: "Teen", tone: "Soft" },
  { name: "Zoe", gender: "Female", age: "Teen", tone: "Gentle" },
  { name: "Ivy", gender: "Female", age: "Teen", tone: "Bright" },
  { name: "Margaret", gender: "Female", age: "Elder", tone: "Soft" },
  { name: "Eleanor", gender: "Female", age: "Elder", tone: "Gentle" },
  { name: "Charlotte", gender: "Female", age: "Elder", tone: "Bright" },
];

